### ISSUE TITLE
ContentDoc with path does not find content

### ISSUE THREAD

**Issue by Mokkapps** [nuxt/content#1142] opened 2022-05-25 12:06 UTC
### Environment

Nuxt CLI v3.0.0-rc.3-27550969.a4a3cff                                        12:03:02
RootDir: /sandbox                                                            12:03:05
Nuxt project info:                                                           12:03:05

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.3-27550969.a4a3cff`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.0`, `@nuxt/ui@0.1.1-27555426.2ead323`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt3-contentv2-blog-demo-zokde1

### Describe the bug

I want to use ContentDoc to query blog posts under `content/blog` by specifying `path="/blog"` in `ContentDoc` component.

If I enter `<BASE_URL>/blog/my-article` I always see the fallback code inside the `#not-found` slot instead of the `index.md` located at that path.

**Comment by Tahul** [comment] 2022-05-25 14:12
Hello @Mokkapps 🙂

This PR should resolve the issue once merged: https://github.com/nuxt/content/pull/1143

Thanks for reporting the bug!

**Comment by R0N1n-dev** [comment] 2022-06-08 10:20
So what is the actual fix for this, still not getting it

**Closed** 2022-06-08 10:50 UTC

**Comment by zdravkov** [comment] 2022-11-06 09:36
The error could also appear if you accidentally place the 'content'  under another directory :) - not the root directory. If you have done it and the fixed it you should clear your cache in order to have it working :)

**Comment by Foddie2** [comment] 2023-09-26 21:07
Still getting this error

**Comment by nobkd** [comment] 2023-09-26 21:33
Hello @Foddie2
Are you able provide a reproduction e.g. with [Stackblitz](https://nuxt.new/s/content) or can you provide a log?
Thank you.

**Comment by CodyBontecou** [comment] 2023-10-31 19:38
I'm seeing this issue when I place the dynamic slug within a nested directory. I.e. `pages/blog/[...slug].vue`.

Here's a reproduction: https://stackblitz.com/github/nuxt/starter/tree/content?file=pages%2F%5B...slug%5D.vue

**Comment by nobkd** [comment] 2023-10-31 20:14
@CodyBontecou 
In your example, you have to use `<ContentDoc path="/" />`, to get the content from the base `content/`directory.
`[...slug].vue` tries takes the default path where it resides, so it looks for Markdown in `content/blog/`.

---

Stackblitz does fail to find `/`, because there is no such path, try adding `/blog/` to the url.

**Comment by CodyBontecou** [comment] 2023-10-31 21:55
Hey @nobkd that seems to fix my immediate issue, thank you.

**Comment by rockfang** [comment] 2023-12-20 08:21
For me. It's worked in development mode. but not wokinh in production mode

**Comment by zaviermiller** [comment] 2024-01-25 20:20
> For me. It's worked in development mode. but not working in production mode

I am getting the same thing. Turning `ssr: false` makes it work, but then I'm losing a lot of the benefits of nuxt.

**Comment by coverspace** [comment] 2024-02-24 16:05
Is this problem being resolved? I have the same problem here

**Comment by DenysMenfredy** [comment] 2024-03-26 13:25
same here, it works in development mode, but not working in production mode. And I don't want to set ```ssr: false```

**Comment by thanhthinh95** [comment] 2024-04-19 07:38
Oh. I am using "@nuxt/content": "^2.12.1" and still encountering a similar error.

**Comment by khaledOghli** [comment] 2024-05-17 07:09
use the path attr, and set the value to your content/docs folder for example 
content/docs/index.md

<ContentDoc path="/docs" />

**Comment by AntonyZ89** [comment] 2024-11-17 22:22
Hello people from future 👽🛸

If you have middleware blocking access from unauthenticated users on your `/server` folder, it might be blocking requests made by @nuxt/content to `/api/_content/query?params....` To fix this, you need to implement a bypass, something like:

```ts
if (path?.startsWith('/api/_content') {
    return // Ignore the request
}
```

I think this "silent error" could be logged in the console, it cost me a few hours to figure out! XD
