### ISSUE TITLE
CSS classes in Markdown component don't merge with component's root class

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt/content#904] opened 2021-06-04 02:05 UTC
### Version
@nuxt/content: v1.14.0
nuxt: v2.15.5

### Steps to reproduce
1. Create a component `abc.vue`.
```html
<template>
  <div class="level1">
   <div class="level2">
    <slot></slot>
   </div>
  </div>
</template>
```

2. Use it in markdown

```md
<abc class="tw-bg-pink-100">
</abc>
```

### What is Expected?
1. `<abc>` component's root should have two classes, i.e. `level1` and `tw-bg-pink-100`.

### What is actually happening?
1. `<abc>` component only gets the class applied in markdown, i.e. `tw-bg-pink-100`.
2. `level1` class is simply removed.

**Comment by NozomuIkuta** [comment] 2021-06-04 09:05
Duplicate of #831?

**Closed** 2021-06-04 21:18 UTC
Labels: bug
