### ISSUE TITLE
Is it possible to store content in another repo

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt/content#278] opened 2020-07-20 13:23 UTC

**Comment by mathe42** [comment] 2020-07-21 12:30
Just use `git clone` in your content folder.

**Comment by rahulkumarsingh73690** [comment] 2020-07-21 12:32
> Just use `git clone` in your content folder.
> 

I know this method. I am trying to make like nuxt official docs

**Comment by mathe42** [comment] 2020-07-21 12:33
Duplicate of #265

**Closed** 2020-07-21 16:22 UTC
Labels: question
