### ISSUE TITLE
Routing of index not working

### ISSUE THREAD

**Issue by woldtwerk** [nuxt/content#1262] opened 2022-06-15 18:50 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v18.0.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@7.1.0`
- Builder:          `vite`
- User Config:      `typescript`, `modules`
- Runtime Modules:  `@nuxt/content@2.0.1`
- Build Modules:    `-`

### Reproduction

pnpm dlx nuxi init content-app -t content
pnpm install --shamefully-hoist
pnpm run dev

### Describe the bug

The routing doesn´t match / to index.md. It seems to use the first file alphabetically.

/ -> about.md
![image](https://user-images.githubusercontent.com/32794633/173901977-98f04c32-f5a8-4171-bb5e-8032dee19950.png)

rename about.md to zabout.md
![image](https://user-images.githubusercontent.com/32794633/173902351-e947bf9b-0549-4148-a17c-0ff4d209d241.png)

**Comment by nobkd** [comment] 2022-06-15 20:00
You might want to look at this issue: #1237
And use the edge version of nuxt content as suggested [here](https://github.com/nuxt/content/issues/1237#issuecomment-1152131314)

**Comment by hacknug** [comment] 2022-06-27 20:21
I think we can safely close this as a duplicate of #1237  👍

**Comment by hacknug** [comment] 2022-06-30 12:11
Looks like this has been fixed in the `edge-channel` version. You can follow the instructions on this page to get the latest changes: https://content.nuxtjs.org/guide/migration/edge-channel

**Comment by cpt-n3mo** [comment] 2022-09-03 18:43
might i suggest this to be push to the nuxi cli as well.. as this also happens with `npx nuxi init someProject -t content`

**Comment by farnabaz** [comment] 2022-09-13 09:58
Closing this because in favor of [v2.1.0](https://github.com/nuxt/content/releases/tag/v2.1.0)

**Closed by farnabaz** 2022-09-13 09:58 UTC
