### ISSUE TITLE
Nuxt Content auto-generates path errors

### ISSUE THREAD

**Issue by canrili** [nuxt/content#1504] opened 2022-09-07 09:51 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/github/nuxt/starter/tree/content?file=README.md

### Describe the bug

<img width="812" alt="image" src="https://user-images.githubusercontent.com/35715627/188848302-d942b99c-c7a7-4852-9a23-eb4a20f61cb5.png">
The above screenshot is the description of the official website document, but in the code, the path "/" corresponds to the first md file in the content directory, not index.md

**Comment by farnabaz** [comment] 2022-09-07 11:05
This issue was fixed in [edge channel](https://content.nuxtjs.org/guide/migration/edge-channel) and will be released in 2.1.0.

**Comment by canrili** [comment] 2022-09-07 12:52
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED] "#imports" is not defined (PNPM)

**Comment by farnabaz** [comment] 2022-09-13 09:47
@canrili v2.1.0 is released and the issue is resolved in this version.

If you still had issues with routes, feel free to open a new issue with a small reproduction

**Closed by farnabaz** 2022-09-13 09:47 UTC
