### ISSUE TITLE
Sytling not working with "Getting Started" Dcocumentation

### ISSUE THREAD

**Issue by bertrandm** [nuxt/content#944] opened 2021-08-09 04:55 UTC
When using npm to create a new nuxt-content-docs project and running it using npm run dev, the page styling is completely broken. The twitter/github icons take up 100% of the page size, and the font styling is very small.

When I use yarn to create a new project and run it using yarn, the styling works, albeit with very, very small fonts, not sure if that is the intended styling not.

package.json has the following dependencies for both projects:

  "dependencies": {
    "@nuxt/content-theme-docs": "^0.10.1",
    "nuxt": "^2.15.2"
  }

**Comment by NozomuIkuta** [comment] 2021-08-09 05:48
Possibly duplicate of #826?

**Comment by bertrandm** [comment] 2021-08-09 06:49
They do seem to be related. It would make sense to join these issues.

**Comment by NozomuIkuta** [comment] 2021-08-09 09:43
Thank you for confirmation!
Then let us close this one 🙌

**Closed** 2021-08-09 14:08 UTC
