### ISSUE TITLE
Request to DB is very long

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#1651] opened 2022-11-02 20:46 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@3.2.4`
- Builder:          `vite`
- User Config:      `modules`, `content`, `schemaOrg`
- Runtime Modules:  `@nuxt/content@2.2.1`, `@nuxtjs/tailwindcss@6.1.2`, `nuxt-schema-org@1.1.0-beta.5`, `nuxt-icon@0.1.7`
- Build Modules:    `-`
------------------------------

### Reproduction

Just check https://esteban-soubiran.site and click on links. (deploy on Netlify)

Repo for reproduction: https://github.com/Barbapapazes/esteban-soubiran.site

### Describe the bug

Request the JSON content file take 500ms which is very long to find content in a JSON file.

![image](https://user-images.githubusercontent.com/45267552/199599347-31f14c94-413d-447b-bdd0-16701346c76d.png)
![image](https://user-images.githubusercontent.com/45267552/199599196-96db3f3c-0992-43c6-992a-f3b119bba8e5.png)

**Comment by Barbapapazes** [comment] 2022-11-02 20:55
But, it could be an issue with Netlify because Vercel has more correct time.

https://esteban-soubiran-site.vercel.app/articles

![Uploading image.png…]()

**Comment by Barbapapazes** [comment] 2022-11-02 21:09
But even in local, it's quite slow

**Comment by Atinux** [comment] 2022-11-03 09:21
First of all, beautiful website @Barbapapazes `:`y``

**Comment by Barbapapazes** [comment] 2022-11-03 09:54
Ho thanks @Atinux! Can't wait to finish!

In fact, I use `nuxt build` to deploy it in Netlify. I will try `generate`.

**Comment by Barbapapazes** [comment] 2022-11-03 09:59
Yes, better but the behavior is still quite slow. But time between a click and a page change is quite noticeable. Can't prefetch?

**Comment by Atinux** [comment] 2022-11-03 10:37
This is where it is tricky right now and I want to improve this.

Right now, the document-driven mode is using a Nuxt middleware to fetch the data: https://github.com/nuxt/content/blob/main/src/runtime/plugins/documentDriven.ts

We shall refactor a part of it to have a function that can fetch and save in the state (`useContentState().pages`).

This way, we could leverage the `link:prefetch` hook from Nuxt (https://v3.nuxtjs.org/api/advanced/hooks#app-hooks-runtime) to call this method.

**Comment by Atinux** [comment] 2022-11-03 10:38
On the other hand, when not using `nuxt generate`, we also need a way to cache the API routes once called (since the content won't change until next deployment).

**Comment by Barbapapazes** [comment] 2022-11-03 12:50
We can't add max-age to JSON request? Here, it's at 0 and because we use a hash in the filename, it will change on every deployment.

![image](https://user-images.githubusercontent.com/45267552/199724660-5bbacf56-aa7d-404d-90d6-6f7a5aeedb5e.png)

**Comment by Atinux** [comment] 2022-11-03 13:47
Normally the hash does not change on every deployment since it is generated based on the request name but anyway each new deployment purges the cache (Netlify or Vercel).

The MAX-AGE 0 is part of Netlify/Vercel actually even if those files are static (it is the same for your main page for instance)

**Comment by Barbapapazes** [comment] 2022-11-03 14:49
Ok, I understand. The strange part, to me, is that, when you query directly the URL, it's fast.

URL to query: https://v3.esteban-soubiran.site/api/_content/query/dyiTU2OVmU.json?_params={%22where%22:[{%22_path%22:%22--REGEX+/^%5C%5C/articles%5C%5C//%22}],%22sort%22:[{%22_file%22:1,%22$numeric%22:true}]}&previewToken

![image](https://user-images.githubusercontent.com/45267552/199753545-76b5ee3a-351f-44ab-a36d-c78cbc386953.png)

**Comment by giticon** [comment] 2022-12-30 18:01
> This is where it is tricky right now and I want to improve this.
> 
> Right now, the document-driven mode is using a Nuxt middleware to fetch the data: https://github.com/nuxt/content/blob/main/src/runtime/plugins/documentDriven.ts
> 
> We shall refactor a part of it to have a function that can fetch and save in the state (`useContentState().pages`).
> 
> This way, we could leverage the `link:prefetch` hook from Nuxt (https://v3.nuxtjs.org/api/advanced/hooks#app-hooks-runtime) to call this method.

the problem is not only at the deployment level. There is also in dev mode. 7 articles, 5 seconds before opening the listing in my case. It is highly not recommended to use this module to create static articles as the loading times are too bad from SEO point of view. A modification is needed to have instant loading of the article list and individual articles both in dev mode and in production. Such a module should have a mechanism to handle hundreds/thousands of documents with instant HMR, otherwise it is unusable. 

In document-driven mode, for example, it is much faster, but this forces the developer to activate it, forcing Nuxt to be used in a different way.

Translated with www.DeepL.com/Translator (free version)

**Comment by giticon** [comment] 2022-12-30 18:02
the problem is not only at the deployment level. There is also in dev mode. 7 articles, 5 seconds before opening the listing in my case. It is highly not recommended to use this module to create static articles as the loading times are too bad from SEO point of view. 

A modification is needed to have instant loading of the article list and individual articles both in dev mode and in production. Such a module should have a mechanism to handle hundreds/thousands of documents with instant HMR, otherwise it is unusable. 

In document-driven mode, for example, it is much faster, but this forces the developer to activate it, forcing Nuxt to be used in a different way.

**Comment by Barbapapazes** [comment] 2023-01-19 13:34
Hello, 

Here a project with many components and many md and json files. https://stackblitz.com/edit/github-ocbh9j?file=content/0.index.md

Actually, it's so slow that's unusable. Edit one word take a while so with module like tailwind, there is no way I can use this module.

**Comment by Barbapapazes** [comment] 2023-01-19 14:35
After some research, the body generation take the most of time.

**Comment by Barbapapazes** [comment] 2023-01-19 14:56
In  dev mode, with every files from the reproduction and an empty index.md. I only add some characters, here the results

![image](https://user-images.githubusercontent.com/45267552/213475190-79c7062b-da25-4a0f-b834-a719318dbea4.png)

**Comment by Barbapapazes** [comment] 2023-01-19 23:10
I continue to try why Content can't scale. After deep diving in every functions, it seems that `getContentsList`, which is called multiple time doesn't scale. https://github.com/nuxt/content/blob/main/src/runtime/server/storage.ts#L104

Lower results for only index.md and higher result for the entier Content Doc.
![image](https://user-images.githubusercontent.com/45267552/213582311-6ce88e52-b7eb-4bcf-9a96-693e2184844e.png)

**Comment by Barbapapazes** [comment] 2023-01-19 23:12
The `promise.all` is the slowest part.

With this code 

```ts

export const getContentsList = async (event: H3Event, prefix?: string) => {
  const time = Date.now()
  const keys = await getContentsIds(event, prefix)
  console.log(`[content] getContentsIds: ${Date.now() - time}ms`)
  const contents = await Promise.all(keys.map(key => getContent(event, key)))
  console.log(`[content] getContentsList: ${Date.now() - time}ms`)

  return contents
}
```

The result

![image](https://user-images.githubusercontent.com/45267552/213582890-b9a05fdd-40d0-46f8-bad9-613e2fc28a51.png)

(With the Content Docs)

**Comment by Barbapapazes** [comment] 2023-01-19 23:18
So, I benchmark the function `getContent`.

```ts
export const getContent = async (event: H3Event, id: string): Promise<ParsedContent> => {
  const time = Date.now()
  const contentId = id
  // Handle ignored id
  if (!contentIgnorePredicate(id)) {
    return { _id: contentId, body: null }
  }
  console.log(`[content] contentIgnorePredicate: ${Date.now() - time}ms`)

  if (isPreview(event)) {
    const { key } = getPreview(event)
    const previewId = `preview:${key}:${id}`
    const draft = await sourceStorage.getItem(previewId)
    if (draft) {
      id = previewId
    }
  }
  console.log(`[content] isPreview: ${Date.now() - time}ms`)

  const cached: any = await cacheParsedStorage.getItem(id)
  if (isProduction && cached) {
    return cached.parsed
  }
  console.log(`[content] cacheParsedStorage.getItem: ${Date.now() - time}ms`)

  const meta = await sourceStorage.getMeta(id)
  console.log(`[content] sourceStorage.getMeta: ${Date.now() - time}ms`)
  const hash = ohash({
    meta,
    // Add Content version to the hash, to revalidate the cache on content update
    version: contentConfig.cacheVersion,
    integrity: contentConfig.cacheIntegrity
  })
  if (cached?.hash === hash) {
    return cached.parsed as ParsedContent
  }
  console.log(`[content] hash: ${Date.now() - time}ms`)

  const body = await sourceStorage.getItem(id)
  console.log(`[content] sourceStorage.getItem: ${Date.now() - time}ms`)

  if (body === null) {
    return { _id: contentId, body: null }
  }

  const parsed = await parseContent(contentId, body as string) as ParsedContent
  console.log(`[content] parseContent: ${Date.now() - time}ms`)

  await cacheParsedStorage.setItem(id, { parsed, hash }).catch(() => { })
  console.log(`[content] cacheParsedStorage.setItem: ${Date.now() - time}ms`)

  return parsed
}
```

And results are

```
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 0ms
[content] contentIgnorePredicate: 0ms
[content] isPreview: 1ms
[content] cacheParsedStorage.getItem: 1ms
[content] cacheParsedStorage.getItem: 1ms
[content] cacheParsedStorage.getItem: 1ms
[content] cacheParsedStorage.getItem: 1ms
[content] cacheParsedStorage.getItem: 1ms (repeated 5 times)
[content] cacheParsedStorage.getItem: 2ms
[content] cacheParsedStorage.getItem: 2ms
[content] cacheParsedStorage.getItem: 2ms
[content] cacheParsedStorage.getItem: 2ms
[content] cacheParsedStorage.getItem: 2ms
[content] cacheParsedStorage.getItem: 2ms (repeated 4 times)
[content] sourceStorage.getMeta: 2ms
[content] hash: 2ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 3ms
[content] hash: 3ms
[content] sourceStorage.getMeta: 4ms
[content] hash: 4ms
[content] sourceStorage.getMeta: 4ms
[content] hash: 4ms
[content] sourceStorage.getMeta: 4ms
[content] hash: 4ms
[content] sourceStorage.getMeta: 4ms
[content] hash: 4ms
[content] sourceStorage.getMeta: 4ms
[content] hash: 4ms
[content] sourceStorage.getMeta: 4ms
[content] hash: 4ms
[content] sourceStorage.getMeta: 4ms
[content] hash: 4ms
[content] sourceStorage.getItem: 5ms
[content] parseContent: 6ms
[content] sourceStorage.getItem: 6ms
[content] parseContent: 7ms
[content] sourceStorage.getItem: 7ms
[content] parseContent: 7ms
[content] sourceStorage.getItem: 7ms
[content] parseContent: 7ms
[content] sourceStorage.getItem: 8ms
[content] parseContent: 8ms
[content] sourceStorage.getItem: 8ms
[content] parseContent: 8ms
[content] sourceStorage.getItem: 8ms
[content] parseContent: 8ms
[content] sourceStorage.getItem: 8ms
[content] parseContent: 9ms
[content] sourceStorage.getItem: 9ms
[content] parseContent: 9ms
[content] sourceStorage.getItem: 9ms
[content] parseContent: 9ms
[content] sourceStorage.getItem: 9ms
[content] parseContent: 10ms
[content] sourceStorage.getItem: 10ms
[content] parseContent: 10ms
[content] sourceStorage.getItem: 10ms
[content] parseContent: 10ms
[content] sourceStorage.getItem: 10ms
[content] parseContent: 10ms
[content] sourceStorage.getItem: 11ms
[content] parseContent: 11ms
[content] sourceStorage.getItem: 11ms
[content] parseContent: 11ms
[content] sourceStorage.getItem: 11ms
[content] parseContent: 11ms
[content] sourceStorage.getItem: 11ms
[content] parseContent: 12ms
[content] cacheParsedStorage.setItem: 17ms
[content] cacheParsedStorage.setItem: 17ms
[content] cacheParsedStorage.setItem: 17ms
[content] cacheParsedStorage.setItem: 17ms
[content] cacheParsedStorage.setItem: 22ms
[content] cacheParsedStorage.setItem: 22ms
[content] cacheParsedStorage.setItem: 22ms (repeated 2 times)
[content] cacheParsedStorage.setItem: 27ms
[content] cacheParsedStorage.setItem: 27ms
[content] cacheParsedStorage.setItem: 27ms
[content] cacheParsedStorage.setItem: 27ms
[content] cacheParsedStorage.setItem: 32ms
[content] cacheParsedStorage.setItem: 32ms
[content] cacheParsedStorage.setItem: 32ms (repeated 2 times)
[content] cacheParsedStorage.setItem: 36ms
[content] cacheParsedStorage.setItem: 36ms
```

(With the Content Docs as md file)

**Comment by Barbapapazes** [comment] 2023-01-19 23:29
For the page `0.index.md`, there is 185 requests to this function. Thas a lot.

![image](https://user-images.githubusercontent.com/45267552/213584929-20569825-f401-4777-9ebf-8b3d9b088f4c.png)

Using this code

```ts
let value = 0
export const getContent = async (event: H3Event, id: string): Promise<ParsedContent> => {
  value++
  const time = Date.now()
  const contentId = id
  // Handle ignored id
  if (!contentIgnorePredicate(id)) {
    return { _id: contentId, body: null }
  }
  // console.log(`[content] contentIgnorePredicate: ${Date.now() - time}ms`)

  if (isPreview(event)) {
    const { key } = getPreview(event)
    const previewId = `preview:${key}:${id}`
    const draft = await sourceStorage.getItem(previewId)
    if (draft) {
      id = previewId
    }
  }
  // console.log(`[content] isPreview: ${Date.now() - time}ms`)

  const cached: any = await cacheParsedStorage.getItem(id)
  if (isProduction && cached) {
    return cached.parsed
  }
  console.log(`[content] ${value} cacheParsedStorage.getItem: ${Date.now() - time}ms`)

  const meta = await sourceStorage.getMeta(id)
  // console.log(`[content] sourceStorage.getMeta: ${Date.now() - time}ms`)
  const hash = ohash({
    meta,
    // Add Content version to the hash, to revalidate the cache on content update
    version: contentConfig.cacheVersion,
    integrity: contentConfig.cacheIntegrity
  })
  if (cached?.hash === hash) {
    return cached.parsed as ParsedContent
  }
  // console.log(`[content] hash: ${Date.now() - time}ms`)

  const body = await sourceStorage.getItem(id)
  console.log(`[content] ${value} sourceStorage.getItem: ${Date.now() - time}ms`)

  if (body === null) {
    return { _id: contentId, body: null }
  }

  const parsed = await parseContent(contentId, body as string) as ParsedContent
  // console.log(`[content] parseContent: ${Date.now() - time}ms`)

  await cacheParsedStorage.setItem(id, { parsed, hash }).catch(() => { })
  // console.log(`[content] cacheParsedStorage.setItem: ${Date.now() - time}ms`)

  return parsed
}
```

**Comment by Barbapapazes** [comment] 2023-01-19 23:33
Where does the 185 files come from?

I print the id (which is at the beginning of the function) and this is the result:

```
v1-fr:fr:v1:_dir.yml
content:1.index.md
content:2.get-started.md
content:7.changelog.md
content:8.playground.md
content:9.content-v1.md
content:6.blog:1.announcing-v2.md
content:_partials:hello-world.md
content:3.guide:_dir.yml
content:3.guide:1.writing:1.content-directory.md
content:3.guide:1.writing:2.markdown.md
content:3.guide:1.writing:3.mdc.md
content:3.guide:1.writing:4.json.md
content:3.guide:1.writing:5.yaml.md
content:3.guide:1.writing:6.csv.md
content:3.guide:1.writing:7.document-driven.md
content:3.guide:1.writing:8.vue-component.md
content:3.guide:1.writing:_dir.yml
content:3.guide:5.migration:1.from-v1.md
content:3.guide:5.migration:2.edge-channel.md
content:3.guide:5.migration:_dir.yml
content:3.guide:3.recipes:1.sitemap.md
content:3.guide:3.recipes:_dir.yml
content:3.guide:2.displaying:1.rendering.md
content:3.guide:2.displaying:2.querying.md
content:3.guide:2.displaying:3.navigation.md
content:3.guide:2.displaying:4.typescript.md
content:3.guide:2.displaying:_dir.yml
content:3.guide:4.deploy:1.node-server.md
content:3.guide:4.deploy:2.static-hosting.md
content:3.guide:4.deploy:_dir.yml
content:4.api:3.configuration.md
content:4.api:4.advanced.md
content:4.api:_dir.yml
content:4.api:1.components:1.content-doc.md
content:4.api:1.components:2.content-list.md
content:4.api:1.components:2.content-renderer.md
content:4.api:1.components:3.content-navigation.md
content:4.api:1.components:4.content-query.md
content:4.api:1.components:5.markdown.md
content:4.api:1.components:6.content-slot.md
content:4.api:1.components:7.prose.md
content:4.api:1.components:_dir.yml
content:4.api:2.composables:1.query-content.md
content:4.api:2.composables:2.fetch-content-navigation.md
content:4.api:2.composables:3.unwrap.md
content:4.api:2.composables:4.use-document-driven.md
content:4.api:2.composables:5.use-content-helpers.md
content:4.api:2.composables:6.use-content-head.md
content:4.api:2.composables:_dir.yml
content:5.examples:_dir.yml
content:5.examples:1.essentials:1.hello-world.md
content:5.examples:1.essentials:2.document-driven.md
content:5.examples:1.essentials:_dir.yml
content:5.examples:4.queries:1.where.md
content:5.examples:4.queries:2.only.md
content:5.examples:4.queries:3.without.md
content:5.examples:4.queries:4.skip-limit.md
content:5.examples:4.queries:_dir.yml
content:5.examples:3.mdc:1.inline-components.md
content:5.examples:3.mdc:2.nested-components.md
content:5.examples:3.mdc:3.props.md
content:5.examples:3.mdc:4.slots.md
content:5.examples:3.mdc:_dir.yml
content:5.examples:5.navigation:1.fetch-content-navigation.md
content:5.examples:5.navigation:2.use-route.md
content:5.examples:5.navigation:_dir.yml
content:5.examples:6.templates:1.content-wind.md
content:5.examples:6.templates:_dir.yml
v1:v1:_dir.yml
v1:v1:1.getting-started:1.introduction.md
v1:v1:1.getting-started:2.installation.md
v1:v1:1.getting-started:3.writing.md
v1:v1:1.getting-started:4.fetching.md
v1:v1:1.getting-started:5.displaying.md
v1:v1:1.getting-started:6.configuration.md
v1:v1:1.getting-started:7.advanced.md
v1:v1:1.getting-started:_dir.yml
v1:v1:3.community:1.snippets.md
v1:v1:3.community:2.integrations.md
v1:v1:2.examples:1.basic.md
v1:v1:2.examples:2.tailwindcss-typography.md
v1:v1:2.examples:3.docs-theme.md
[content] getContentsIds: 20ms
v1-fr:fr:v1:_dir.yml
content:1.index.md
content:2.get-started.md
content:7.changelog.md
content:8.playground.md
content:9.content-v1.md
content:_partials:hello-world.md
content:6.blog:1.announcing-v2.md
content:4.api:3.configuration.md
content:4.api:4.advanced.md
content:4.api:_dir.yml
content:4.api:1.components:1.content-doc.md
content:4.api:1.components:2.content-list.md
content:4.api:1.components:2.content-renderer.md
content:4.api:1.components:3.content-navigation.md
content:4.api:1.components:4.content-query.md
content:4.api:1.components:5.markdown.md
content:4.api:1.components:6.content-slot.md
content:4.api:1.components:7.prose.md
content:4.api:1.components:_dir.yml
content:4.api:2.composables:1.query-content.md
content:4.api:2.composables:2.fetch-content-navigation.md
content:4.api:2.composables:3.unwrap.md
content:4.api:2.composables:4.use-document-driven.md
content:4.api:2.composables:5.use-content-helpers.md
content:4.api:2.composables:6.use-content-head.md
content:4.api:2.composables:_dir.yml
content:3.guide:_dir.yml
content:3.guide:1.writing:1.content-directory.md
content:3.guide:1.writing:2.markdown.md
content:3.guide:1.writing:3.mdc.md
content:3.guide:1.writing:4.json.md
content:3.guide:1.writing:5.yaml.md
content:3.guide:1.writing:6.csv.md
content:3.guide:1.writing:7.document-driven.md
content:3.guide:1.writing:8.vue-component.md
content:3.guide:1.writing:_dir.yml
content:3.guide:4.deploy:1.node-server.md
content:3.guide:4.deploy:2.static-hosting.md
content:3.guide:4.deploy:_dir.yml
content:3.guide:3.recipes:1.sitemap.md
content:3.guide:3.recipes:_dir.yml
content:3.guide:5.migration:1.from-v1.md
content:3.guide:5.migration:2.edge-channel.md
content:3.guide:5.migration:_dir.yml
content:3.guide:2.displaying:1.rendering.md
content:3.guide:2.displaying:2.querying.md
content:3.guide:2.displaying:3.navigation.md
content:3.guide:2.displaying:4.typescript.md
content:3.guide:2.displaying:_dir.yml
content:5.examples:_dir.yml
content:5.examples:1.essentials:1.hello-world.md
content:5.examples:1.essentials:2.document-driven.md
content:5.examples:1.essentials:_dir.yml
content:5.examples:3.mdc:1.inline-components.md
content:5.examples:3.mdc:2.nested-components.md
content:5.examples:3.mdc:3.props.md
content:5.examples:3.mdc:4.slots.md
content:5.examples:3.mdc:_dir.yml
content:5.examples:5.navigation:1.fetch-content-navigation.md
content:5.examples:5.navigation:2.use-route.md
content:5.examples:5.navigation:_dir.yml
content:5.examples:4.queries:1.where.md
content:5.examples:4.queries:2.only.md
content:5.examples:4.queries:3.without.md
content:5.examples:4.queries:4.skip-limit.md
content:5.examples:4.queries:_dir.yml
content:5.examples:6.templates:1.content-wind.md
content:5.examples:6.templates:_dir.yml
v1:v1:_dir.yml
v1:v1:1.getting-started:1.introduction.md
v1:v1:1.getting-started:2.installation.md
v1:v1:1.getting-started:3.writing.md
v1:v1:1.getting-started:4.fetching.md
v1:v1:1.getting-started:5.displaying.md
v1:v1:1.getting-started:6.configuration.md
v1:v1:1.getting-started:7.advanced.md
v1:v1:1.getting-started:_dir.yml
v1:v1:3.community:1.snippets.md
v1:v1:3.community:2.integrations.md
v1:v1:2.examples:1.basic.md
v1:v1:2.examples:2.tailwindcss-typography.md
v1:v1:2.examples:3.docs-theme.md
```

It seems that every file of the project is loaded and parsed every time I hit save. This can explain why this is very slow and does not scale well

**Comment by Barbapapazes** [comment] 2023-01-19 23:39
The issue is here.

https://github.com/nuxt/content/blob/main/src/runtime/server/storage.ts#L77

Is there any way to use the event to filter keys?

**Comment by oripka** [comment] 2023-01-20 08:35
Salut, thanks for looking into this. I feel most people are just using `nuxi generate` to get around these issues. It seems you profiled the development mode, but I assume this `getContent` function might also cause the slow production?

**Comment by Barbapapazes** [comment] 2023-01-20 08:39
Yes, I'm looking for a solution in dev mode. In fact, `nuxi generate` works well in prod.

**Comment by Barbapapazes** [comment] 2023-01-20 15:44
Here a sum up. I added a log after this function https://github.com/nuxt/content/blob/main/src/runtime/server/storage.ts#L106 with the result.

```
[getContentsList] end: 9864ms {
  where: [ { _partial: [Object], navigation: [Object] } ],
  without: [ 'body' ],
  surround: { query: '/guide/writing/markdown' },
  sort: [ { _file: 1, '$numeric': true } ]
} [
  'v1-fr:fr:v1:_dir.yml',
  'content:1.index.md',
  'content:2.get-started.md',
  'content:7.changelog.md',
  'content:8.playground.md',
  'content:9.content-v1.md',
  'content:6.blog:1.announcing-v2.md',
  'content:_partials:hello-world.md',
  'content:3.guide:_dir.yml',
  'content:3.guide:2.displaying:1.rendering.md',
  'content:3.guide:2.displaying:2.querying.md',
  'content:3.guide:2.displaying:3.navigation.md',
  'content:3.guide:2.displaying:4.typescript.md',
  'content:3.guide:2.displaying:_dir.yml',
  'content:3.guide:1.writing:1.content-directory.md',
  'content:3.guide:1.writing:2.markdown.md',
  'content:3.guide:1.writing:3.mdc.md',
  'content:3.guide:1.writing:4.json.md',
  'content:3.guide:1.writing:5.yaml.md',
  'content:3.guide:1.writing:6.csv.md',
  'content:3.guide:1.writing:7.document-driven.md',
  'content:3.guide:1.writing:8.vue-component.md',
  'content:3.guide:1.writing:_dir.yml',
  'content:3.guide:5.migration:1.from-v1.md',
  'content:3.guide:5.migration:2.edge-channel.md',
  'content:3.guide:5.migration:_dir.yml',
  'content:3.guide:3.recipes:1.sitemap.md',
  'content:3.guide:3.recipes:_dir.yml',
  'content:3.guide:4.deploy:1.node-server.md',
  'content:3.guide:4.deploy:2.static-hosting.md',
  'content:3.guide:4.deploy:_dir.yml',
  'content:4.api:3.configuration.md',
  'content:4.api:4.advanced.md',
  'content:4.api:_dir.yml',
  'content:4.api:1.components:1.content-doc.md',
  'content:4.api:1.components:2.content-list.md',
  'content:4.api:1.components:2.content-renderer.md',
  'content:4.api:1.components:3.content-navigation.md',
  'content:4.api:1.components:4.content-query.md',
  'content:4.api:1.components:5.markdown.md',
  'content:4.api:1.components:6.content-slot.md',
  'content:4.api:1.components:7.prose.md',
  'content:4.api:1.components:_dir.yml',
  'content:4.api:2.composables:1.query-content.md',
  'content:4.api:2.composables:2.fetch-content-navigation.md',
  'content:4.api:2.composables:3.unwrap.md',
  'content:4.api:2.composables:4.use-document-driven.md',
  'content:4.api:2.composables:5.use-content-helpers.md',
  'content:4.api:2.composables:6.use-content-head.md',
  'content:4.api:2.composables:_dir.yml',
  'content:5.examples:_dir.yml',
  'content:5.examples:1.essentials:1.hello-world.md',
  'content:5.examples:1.essentials:2.document-driven.md',
  'content:5.examples:1.essentials:_dir.yml',
  'content:5.examples:3.mdc:1.inline-components.md',
  'content:5.examples:3.mdc:2.nested-components.md',
  'content:5.examples:3.mdc:3.props.md',
  'content:5.examples:3.mdc:4.slots.md',
  'content:5.examples:3.mdc:_dir.yml',
  'content:5.examples:4.queries:1.where.md',
  'content:5.examples:4.queries:2.only.md',
  'content:5.examples:4.queries:3.without.md',
  'content:5.examples:4.queries:4.skip-limit.md',
  'content:5.examples:4.queries:_dir.yml',
  'content:5.examples:5.navigation:1.fetch-content-navigation.md',
  'content:5.examples:5.navigation:2.use-route.md',
  'content:5.examples:5.navigation:_dir.yml',
  'content:5.examples:6.templates:1.content-wind.md',
  'content:5.examples:6.templates:_dir.yml',
  'v1:v1:_dir.yml',
  'v1:v1:1.getting-started:1.introduction.md',
  'v1:v1:1.getting-started:2.installation.md',
  'v1:v1:1.getting-started:3.writing.md',
  'v1:v1:1.getting-started:4.fetching.md',
  'v1:v1:1.getting-started:5.displaying.md',
  'v1:v1:1.getting-started:6.configuration.md',
  'v1:v1:1.getting-started:7.advanced.md',
  'v1:v1:1.getting-started:_dir.yml',
  'v1:v1:2.examples:1.basic.md',
  'v1:v1:2.examples:2.tailwindcss-typography.md',
  'v1:v1:2.examples:3.docs-theme.md',
  'v1:v1:3.community:1.snippets.md',
  'v1:v1:3.community:2.integrations.md'
]
```

As we can see, we want `/guide/writing/markdown` but every files in keys are rendered.

**Comment by Barbapapazes** [comment] 2023-01-20 15:51
I think, I'm close to the issue.

```

**Comment by Barbapapazes** [comment] 2023-01-20 16:08
`surround` and `navigation` are the issue because the event don't filter keys so every page are re-render!

![image.png](https://volta.s3.fr-par.scw.cloud/image_242efd5604.png)

**Comment by Barbapapazes** [comment] 2023-01-20 16:10
@Atinux and @farnabaz ? Don't know how to solve this but I'm pretty sure that this is the issue. 👌

**Comment by Barbapapazes** [comment] 2023-01-22 14:58
Another unexpected behavior is that when a page is loaded, the AST from a MD file is written. But when I reload the page, the content file is deleted and rewritten.

Exemple:

I load `/`, content is written in `1.index.md`

![image](https://user-images.githubusercontent.com/45267552/213922553-a867666b-f5b9-4944-8560-55346764ac61.png)

When I reload, content is drained.

![image](https://user-images.githubusercontent.com/45267552/213922602-164e9072-5358-4add-917d-7bb3149967ad.png)

And then rewritten.

**Comment by Barbapapazes** [comment] 2023-01-22 15:15
Found it ! [Theres line are the issue](https://github.com/nuxt/content/blob/main/src/runtime/server/storage.ts#L134). When page is reloaded, navigation is rebuild. To build navigation, every md files need to be parsed. But, every time, cache is invalidated so every md files are rebuild.

A log of meta and hash 

![image](https://user-images.githubusercontent.com/45267552/213923494-ea55e359-378a-4720-a09d-cec16b48fe15.png)

**Comment by Barbapapazes** [comment] 2023-01-22 15:16
I will continue to search a way to fix this.

**Comment by Barbapapazes** [comment] 2023-01-22 15:24
Here, with the file `1.index.md`. 3 requests in a row and 3 differents hash. I think that `atime` (I don't know what it means, A stand for?)

![image](https://user-images.githubusercontent.com/45267552/213923835-1f27ecd4-fe77-48aa-ad49-65b26a37b9eb.png)

**Comment by Barbapapazes** [comment] 2023-01-22 15:27
Oh!

`atime` for `accessed time`
`mtime` form `modified time`

**Comment by Barbapapazes** [comment] 2023-01-22 15:29
Yes yes! this is it!

```
  const meta = await sourceStorage.getMeta(id)
  const hash = ohash({
    modified: meta.mtime,
    // Add Content version to the hash, to revalidate the cache on content update
    version: contentConfig.cacheVersion,
    integrity: contentConfig.cacheIntegrity
  })
```

**Comment by Thexumaker** [comment] 2023-02-15 09:26
Any updates on when the fix might be merged?

**Comment by hlassiege** [comment] 2023-02-18 19:36
Very nice ! In dev mode I have also a lot of slowness and it's really painful

Thanks a lot for your work on that

**Closed** 2023-02-21 15:57 UTC
