### ISSUE TITLE
"export 'default' (imported as 'QueryBuilder') was not found in './query-builder'

### ISSUE THREAD

**Issue by benlutz** [nuxt/content#31] opened 2020-05-24 11:47 UTC
First time opening a ticket to git repo, so please forgive me, if I am doing something wrong.

I installed the @nuxt/content package as described in the documentation, but I get the following error in the console: 

>  WARN  in ./.nuxt/content/plugin.client.js                              
> "export 'default' (imported as 'QueryBuilder') was not found in './query-builder'

and 

> Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
>    at Module.eval (query-builder.js?b39a:101)
>    at eval (query-builder.js:166)
>    at Module../.nuxt/content/query-builder.js (app.js:275)
>    at __webpack_require__ (runtime.js:854)
>    at fn (runtime.js:151)
>    at eval (plugin.client.js:15)
>   at Module../.nuxt/content/plugin.client.js (app.js:263)
>    at __webpack_require__ (runtime.js:854)
>    at fn (runtime.js:151)
> at eval (index.js:43)

---
@nuxt/content: v1.0.0
nuxt: v2.11.0
---

as a result, {export default} will not work on any page.

**Comment by benlutz** [comment] 2020-05-24 12:44
in ./content/query-builder

i changed
> module.exports = QueryBuilder
to
> export default QueryBuilder

after coming across this issue:
https://github.com/webpack/webpack/issues/4039#issuecomment-273804003

And it seems to fix it for me.

**Comment by benjamincanac** [comment] 2020-05-24 15:23
Hey @benlutz, 

What are you trying to do? This error happens while generating your app?

Could you provide a reproduction link?

**Comment by benlutz** [comment] 2020-05-24 16:40
Hey @benjamincanac,
thank you for your quick reply! I was just using it in development mode. Unfortunatley I don't have a reproduction link ready (an to be honest, I am too much of a junior to figure out how to do it right now). I was just trying to implement a light and fast blog for my ongoing project.

But I could fix this issue by going into 
> node_modules/@nuxt/content/lib/templates/query-builder.js

and replacing

> module.exports = QueryBuilder

with

> export default QueryBuilder

This seems to fix this issue. Because after searching for this error message
> Uncaught TypeError: Cannot assign to read only property 'exports' of object '#'

I came across [this issue](https://github.com/webpack/webpack/issues/4039#issuecomment-273804003), explaining that

> you can't mix import and module.exports

and that is basically what was happening:
> module.exports = Query Builder

in query-builder.js and

> import QueryBuilder from './query-builder' 

in plugin.client.js


I hope this makes sense...

**Comment by benlutz** [comment] 2020-05-24 18:11
okay, this seemed to be a problem with my slightly older nuxt-version (or something else that was outdated). With everthing up to date now, it works as expected. Sorry for the Inconvenience!

**Comment by benjamincanac** [comment] 2020-05-25 11:15
@benlutz Glad it worked out!

**Comment by andrewlaskey** [comment] 2020-05-27 18:03
I ran into this same issue as well.

I had to update `node_modules/@nuxt/content/lib/templates/query-builder.js` from `module.exports = QueryBuilder` to `export default QueryBuilder`

I'm using `nuxt@2.11.0`

**Comment by benlutz** [comment] 2020-05-27 18:17
check whether you have outdated modules with `npm outdated`

I am not sure which module was not up to date in my case, but updating all fixed the issue for me without changing anything in the module!

**Comment by JonathanSchndr** [comment] 2021-09-28 12:38
> I ran into this same issue as well.
> 
> I had to update `node_modules/@nuxt/content/lib/templates/query-builder.js` from `module.exports = QueryBuilder` to `export default QueryBuilder`
> 
> I'm using `nuxt@2.11.0`

wow.. same error in "nuxt": "^2.15.8", and "@nuxt/content": "^1.14.0",.
this workaround works. thanks!

**Comment by NozomuIkuta** [comment] 2021-09-28 15:17
@JonathanSchndr 

Thank you for submitting the PR.

Would you provide a reproduction link or steps (from setting up of a project), so that I can review it validly?

**Comment by NozomuIkuta** [comment] 2021-09-28 15:18
Let me reopen this issue at this moment, in case the issue is not yet fixed.

**Comment by JonathanSchndr** [comment] 2021-09-28 15:41
> Let me reopen this issue at this moment, in case the issue is not yet fixed.

hi @NozomuIkuta thanks for your fast answer. i couldn't recreate the problem now after i deleted and recreated my node_moduls and lock. so i deleted the PR too. i think there was something messed up and he had been working with an old nuxt version. sorry for the trouble! 

the only bug that has really remained is the error handling when it can't find a file. It then always throws the path and says not found - even though the path exists.

**Comment by NozomuIkuta** [comment] 2021-09-29 13:27
@JonathanSchndr 

Thank you for confirmation!

> the only bug that has really remained is the error handling when it can't find a file. It then always throws the path and says not found - even though the path exists.

Since the original content of this issue can be said to have been resolved, I appreciate if you open another issue to deal with this one.
Let me close this issue now...

**Closed by NozomuIkuta** 2021-09-29 13:27 UTC
Labels: bug
