### ISSUE TITLE
Full static mode $content options not applying to the fetch query

### ISSUE THREAD

**Issue by KirillTregubov** [nuxt/content#335] opened 2020-08-03 16:06 UTC
Hi all!

I am trying to compute my own timeToRead property, but for this I need access to the `text` variable (which returns the original markdown content in a text variable) which can be specified in an options object to $content. My problem is that providing this object in full static mode (introduced in nuxt v2.13.0), it seems that this variable is not requested in production. Therefore I assume that the options object is not being applied in this generation mode.

Although it would be nice to have a timeToRead property similar to what Gridsome has, this problem can also be solved if the options object was correctly applied to the $content query.

### Version
@nuxt/content: v1.5.3
nuxt: v2.14.0

### Reproduction Link
Universal SSR sandbox: https://codesandbox.io/s/lucid-taussig-wenze?file=/nuxt.config.js
Full static sandbox: https://codesandbox.io/s/compassionate-leaf-qkjj0?file=/nuxt.config.js

### Steps to reproduce
- Fork the provided @nuxt/content sandbox: https://codesandbox.io/s/nuxtcontent-demo-l164h
- Open `package.json` and edit the dev script to be `"MINIMAL=1 CSB=1 nuxt generate && nuxt start"`.
  - This runs nuxt in a production environment full static mode and follows the steps outlined in [this nuxt blog post](https://nuxtjs.org/blog/going-full-static/).
- Open `pages/_slug.vue` and change line 13 to `const page = await $content(slug, { text: true })`
  - This follows [the nuxt/content docs on providing options to the $content query](https://content.nuxtjs.org/fetching/#contentpath-options).
- Still on `pages/_slug.vue`, declare a paragraph element that shows whether or not page.text is accessible. I did this on a new line underneath line 4. `<p>{{ page.text ? 'page.text exists' : 'page.text missing' }}</p>`

### What is Expected?
For the page object to have the original markdown content in a text variable and for the paragraph element to show `page.text exists` to reflect it being passed in as an option.

### What is actually happening?
The page object does not have a `text` variable and the paragraph shows `page.text missing` when the nuxt project is run in full static mode with the production environment.
Interesting to note that this bug does not exist when you are in the full static mode but with the development environment nor when the nuxt app is server-side rendered.

**Comment by cogor** [comment] 2020-08-04 08:30
Hi, in my blog I used [reading-time](https://www.npmjs.com/package/reading-time)
And just added time to hook in nuxt.config.js
```javascript
  hooks: {
    'content:file:beforeInsert': (document) => {
      if (document.extension === '.md') {
        const { minutes } = require('reading-time')(document.text)

        document.readingTime = minutes
      }
    },
  },
```

**Comment by KirillTregubov** [comment] 2020-08-04 09:08
> Hi, in my blog I used [reading-time](https://www.npmjs.com/package/reading-time)
> And just added time to hook in nuxt.config.js
> 
> ```js
>   hooks: {
>     'content:file:beforeInsert': (document) => {
>       if (document.extension === '.md') {
>         const { minutes } = require('reading-time')(document.text)
> 
>         document.readingTime = minutes
>       }
>     },
>   },
> ```

This is a really elegant solution to my goal, thanks a ton! I still feel like the bug itself should be investigated because it might cause unwanted behaviour for others who pass in options to $content.

**Comment by benjamincanac** [comment] 2020-08-04 09:15
@KirillTregubov Indeed as mentioned @cogor, you have to use hooks to achieve this, you can find an exemple here: https://content.nuxtjs.org/advanced#contentfilebeforeinsert.

This is not a bug, `text` is not returned by the $content API by choice to avoid big payloads.

**Comment by KirillTregubov** [comment] 2020-08-04 09:18
> @KirillTregubov Indeed as mentioned @cogor, you have to use hooks to achieve this, you can find an exemple here: https://content.nuxtjs.org/advanced#contentfilebeforeinsert.
> 
> This is not a bug, `text` is not returned by the $content API by choice to avoid big payloads.

@benjamincanac Ah gotcha, this makes much more sense. However, text is still returned by the API when run in universal / SSR mode. Is that the unwanted behaviour then?

**Comment by benjamincanac** [comment] 2020-08-04 14:02
@KirillTregubov No this shouldn't be the case 🤔 Could you provide a reproduction when this happens?

**Comment by KirillTregubov** [comment] 2020-08-04 16:45
@benjamincanac this sandbox builds in production mode: https://codesandbox.io/s/lucid-taussig-wenze?file=/nuxt.config.js

**Comment by benjamincanac** [comment] 2020-08-05 08:44
@KirillTregubov Oh I see, your issue is more `text` is not returned on client-side when the `{ text: true }` option is passed and using `nuxt generate`.

Let me look into it!

**Comment by benjamincanac** [comment] 2020-08-05 11:44
Nice catch! Will be fixed in next release ☺️

**Closed** 2020-08-05 11:43 UTC
Labels: bug
