### ISSUE TITLE
Fetch on list of subdirectories under a path

### ISSUE THREAD

**Issue by rrrepos** [nuxt/content#1011] opened 2022-02-15 11:25 UTC
Is there a way to fetch the subdirectories in Nuxt?

For example if I have a content structure as follows:

```
content
   course-c1
      subj-c1s1
         content.md
      subj-c1s2
         content.md
      ...
   course-c2
      subj-c2s1
         content.md
      subj-c2s2
         content.md
      ...
   ....
```
I would like to:

1. fetch all the courses generating an array ['course-c1', 'course-c2'] and another
2. fetch all subjects of course course-c1 which should generate ['subj-c1s1', 'subj-c1s2']

Thanks

**Comment by NozomuIkuta** [comment] 2022-02-15 13:08
Essentially duplicate of #967

**Closed by NozomuIkuta** 2022-02-15 13:08 UTC
Labels: question
