### ISSUE TITLE
there must be something wrong at skip() of queryCollections() in nuxt content 3， it doesnt work when i use it ，

### ISSUE THREAD

**Issue by shidaizaiweixiao** [nuxt/content#2867] opened 2024-11-24 15:12 UTC
### Environment

npx nuxi info

### Version

v3

### Reproduction

i develop it at local

### Description

there must be something wrong at skip() of queryCollections() in nuxt content 3， it doesnt work when i use it ，

### Logs

```shell-script

```

**Comment by farnabaz** [comment] 2024-11-25 13:45
Thanks for the issue, indeed there was an issue in the query builder. The issue is fixed in https://github.com/nuxt/content/commit/097cc7744be2c7c212f4c24aac07e4aaeaa6a1a3

The fix will be released in the next alpha but meanwhile, you can test using commit release `npm i https://pkg.pr.new/@nuxt/content@097cc77`

**Comment by zzdaddy** [comment] 2024-11-28 05:02
same, maybe i should wait next next next  version ...

**Comment by farnabaz** [comment] 2024-11-28 08:36
@zzdaddy Did you try with the commit release? `npm i https://pkg.pr.new/@nuxt/content@097cc77`

**Comment by zzdaddy** [comment] 2024-12-06 06:20
> [@zzdaddy](https://github.com/zzdaddy) Did you try with the commit release? `npm i https://pkg.pr.new/@nuxt/content@097cc77`

not yet now😁 i'll try it. thanks!

**Comment by zzdaddy** [comment] 2024-12-06 07:31
"@nuxt/content": "https://pkg.pr.new/@nuxt/content@097cc77"

👆it's worked

**Closed** 2024-12-09 15:58 UTC
Labels: bug, v3
