### ISSUE TITLE
Fix <img> tag in <p> for ProseImg component

### ISSUE THREAD

**Issue by helltraitor** [nuxt/content#2135] opened 2023-07-03 14:13 UTC
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxt/content@2.7.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-43d3pv?file=components%2Fcontent%2FProseImg.vue

### Describe the bug

It's fine to have img in p, when no component provided. But in case when I want to create my own image component, it is also wrapped by p tag.

### Additional context

Possible workaround is to create postprocessor over fetched `data` and then pass it as usual

**Comment by nobkd** [comment] 2023-07-03 15:00
Indirect duplicate of #1537

**Closed** 2023-07-03 15:05 UTC
