### ISSUE TITLE
queryContent doesn't work after nuxt build

### ISSUE THREAD

**Issue by kevinhaeni** [nuxt/content#2593] opened 2024-03-23 19:34 UTC
### Environment

"@nuxt/content": "^2.12.0",
"nuxt": "^3.10.2",
"vue": "^3.4.19",

### Reproduction

- content/
- -- doc_1.json
- -- doc_2.json
- app.vue
- nuxt.config.ts
- pages/
- -- [...slug].vue

slug.vue:
```
const slug = route.params.slug[0];
const { data, pending, error, refresh } = await useAsyncData(slug, () => queryContent(slug).findOne());
```

nuxt.config.ts:
```
import path from "node:path";

export default defineNuxtConfig({
  ssr: true,
  modules: [
    '@nuxt/content'
  ],
  content: {
    content: {
      driver: 'fs',
      base: path.resolve(__dirname, 'content')
    },
  },
  routeRules: {
    "/**": {
      prerender: false,
    },
  },
});
```

### Describe the bug

When running `nuxt dev`, everything works fine: calling localhost:3000/doc_1 shows the content of doc_1.json:

However, when running `nuxt build` and `node .output/server/index.mjs` and doing the same request, I'm getting:

```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading '_path')
  at ./.output/server/chunks/nitro/node-server.mjs:8163:52  
  at Array.find (<anonymous>)  
  at fetchDirConfig (./.output/server/chunks/nitro/node-server.mjs:8163:32)  
  at ./.output/server/chunks/nitro/node-server.mjs:8197:63  
  at Array.reduce (<anonymous>)  
  at ./.output/server/chunks/nitro/node-server.mjs:8197:39  
  at async Object.handler (./.output/server/chunks/nitro/node-server.mjs:8528:21)  
  at async Object.handler (./.output/server/chunks/nitro/node-server.mjs:2967:19)  
  at async toNodeHandle (./.output/server/chunks/nitro/node-server.mjs:3233:7)  
  at async ufetch (./.output/server/chunks/nitro/node-server.mjs:3599:17)

```

I would expect that queryContent fetches the files from /content directory. I could swear that some days ago it did fetch data from some nuxt-content cache file (which would also not be good as my data in /content is dynamic.

### Additional context

What confuses me is that under .output/server/chunks/raw/ I see a doc_1.mjs and a doc_2.mjs and the error seems to result from loading these files.

**Comment by farnabaz** [comment] 2024-03-23 20:12
Do you mind creating a sample reproduction using the starter? https://nuxt.new/c/content

**Comment by kevinhaeni** [comment] 2024-03-23 20:36
I tried but even when I run build in the unmodified starter, I'm getting a:
[8:35:59 PM]  ERROR  Nuxt Build Error: "joinRelativeURL" is not exported by "node_modules/ufo/dist/index.mjs", imported by "virtual:nuxt:/workspace/.nuxt/paths.mjs".

**Comment by Ahmard** [comment] 2024-03-25 10:39
![Screenshot from 2024-03-25 11-38-38](https://github.com/nuxt/content/assets/44737217/b2ce6086-f19d-44dc-b24e-c170cae92fec)

Facing the same problem here too

**Comment by Ahmard** [comment] 2024-03-25 12:01
Try upgrading your Nuxt version, it'll work,
`nuxi upgrade --force`

**Comment by some-user123** [comment] 2024-03-25 14:06
Try `pnpm up ufo` (or corresponding command in your package manager).

**Comment by kevinhaeni** [comment] 2024-03-25 21:53
thanks! Here you go: [Sample](https://codesandbox.io/p/devbox/angry-noether-xx6tw7?file=%2Fpages%2F%5B...slug%5D.vue%3A17%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu4jlze300073b6m3ulwsl94%2522%252C%2522sizes%2522%253A%255B62.16255442670537%252C37.83744557329463%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu4jlze300023b6mmebmy0tl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu4jlze300043b6mkwldlskk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu4jlze300063b6ml40rgsws%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu4jlze300023b6mmebmy0tl%2522%253A%257B%2522id%2522%253A%2522clu4jlze300023b6mmebmy0tl%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu4jlze300063b6ml40rgsws%2522%253A%257B%2522id%2522%253A%2522clu4jlze300063b6ml40rgsws%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clu7he86p037v3b6k1qifmyhy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fdoc_1%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu7he86p037v3b6k1qifmyhy%2522%257D%252C%2522clu4jlze300043b6mkwldlskk%2522%253A%257B%2522id%2522%253A%2522clu4jlze300043b6mkwldlskk%2522%252C%2522activeTabId%2522%253A%2522clu7he3vo034r3b6k5vqdsyo6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu7h5nxz00rs3b6k4x7q0pqg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu7h5nzh019sdiis0dw2fhvk%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522clu7h9xnk021p3b6kr2lxj45p%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clu7he3vo034r3b6k5vqdsyo6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A18.358522250209916%257D)

When using nuxt dev and opening :3000/doc_1
it works, when doing the same after `nuxt build` and `node .output/server/index.mjs`, I'm still getting the error `[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading '_path')`

**Comment by juane1000** [comment] 2024-04-03 00:43
Can confirm that a nuxi upgrade did the trick. Experienced the issue for the first time today. I was on the current version however. Not sure what went wrong.

**Comment by santiagoaloi** [comment] 2024-04-09 02:19
I would assume its related to a an issue I reported some time ago #2580
Upgrading nuxt to the latest version will also upgrade nitro pack the bug I was hitting was related to Nitro Version: 2.9.1
If this case is resolved, I suggest closing it 🙂

**Comment by kevinhaeni** [comment] 2024-04-09 13:51
I did a npx nuxi upgrade and it's now using: Nuxt 3.11.2 with Nitro 2.9.6   
However, the error still persists for me

**Comment by idesignzone** [comment] 2024-04-12 14:10
I have this problem too. Following

```
const { data } = await useAsyncData(slug, () => queryContent(slug).findOne());
```

works in Dev but not in Prod. Seems like it takes a moment for content to load and gets ignored in process. After a page reload content appears!

**Comment by ABB65** [comment] 2024-04-25 20:02
Unfortunately I have the same error.
While the code below works in dev mode on my blog pages that I prerender with route rules and on the pages I created for some static documents, it does not work after build.

```
const { data: documents } = await useAsyncData('contracts-kvkk-data', () =>
  queryContent<any>('/sozlesmeler-ve-kvkk').find())
```
This code gives me an empty array after build.
 
Route rules are as follows.

```
    'sozlesmeler-ve-kvkk/**': {
      prerender: true,
    },
```

**Comment by EroTiXx** [comment] 2024-05-02 09:28
Same problem, everything works in Dev, but nothing works in Prod, the query returns an empty array

`const { data: posts } = await useAsyncData(path, () => queryContent(path).sort({ date: -1 }).find())`

`"nuxt": "^3.11.2", "@nuxt/content": "^2.12.0"`

The `nuxi upgrade --force` command does nothing

**Provider: CloudFront**

**Comment by cameroncf** [comment] 2024-05-07 09:39
> I tried but even when I run build in the unmodified starter, I'm getting a:
> [8:35:59 PM] ERROR Nuxt Build Error: "joinRelativeURL" is not exported by "node_modules/ufo/dist/index.mjs", imported by "virtual:nuxt:/workspace/.nuxt/paths.mjs".

@kevinhaeni  I'm getting this same error and did a little digging in the lockfile to try and find it's origin. Looks like `ufo@1.4.0` doesn't export `joinRelativeURL` but `ufo@1.5.3` does. Both are in my lockfile, and they seem to track back to a specific version of Rollup and/or Nuxt, but then my head exploded trying to get further.

Did you ever find a resolution to this?

**Comment by richard-edwards** [comment] 2024-05-17 13:08
@cameroncf I tried every iteration of your package.json edit and still the same issue for me. I'm using pnpm as well but I am using Turbo repo so I wonder if that has anything to do with it.

**Comment by CharlieDigital** [comment] 2024-05-27 16:14
@cameroncf 's solution worked for me.  If you are using Yarn, you'll need to use `resolutions` instead of `overrides`:

```json
  "resolutions": {
    "ufo": "1.5.3"
  }
```

(Add at same level as `dependencies`)

**Comment by farnabaz** [comment] 2024-07-09 14:12
Everything should be good with latest module and Nuxt version

**Closed by farnabaz** 2024-07-09 14:12 UTC

**Comment by Aravinda93** [comment] 2024-09-12 11:31
@farnabaz @cameroncf @CharlieDigital 

You mentioned that with the latest Nuxt version, this should be fixed but for some reason even with the latest Nuxt version ` "nuxt": "^3.13.1",` and Nuxt content `"@nuxt/content": "^2.13.2",` I am seeing this issue.

Everything works fine when I run in dev mode, though docker or running locally via `.output` using `node .output/server/index.mjs --port=8080 --hostname=0.0.0.0` but when deployed it is not working.

```javascript
<script setup>
//Get the tag name associated with the route
const route = useRoute();
const tag = route?.params?.tags;
console.log("Tag Obtained from URL : " + tag);

// Fetch all documents
const { data: docs } = await useAsyncData("docs", () => queryContent().find(), {
  server: true,
});

// Filter documents based on the tag
const filteredDocs = computed(() => {
  if (!docs.value) return [];
  const matchingDocs = docs.value.filter((doc) =>
    doc.navigation?.tags?.includes(tag)
  );
  console.log("Matching PAGES : " + JSON.stringify(matchingDocs, null, 4));
  return matchingDocs;
});

//On click of the tags go its respective tags page to list pages matching similar tags
const navigateToTag = (event, tag) => {
  event.preventDefault();
  useRouter().push(`/tags/${tag}/`);
};
</script>
```

Here `docs` value I am getting empty due to which unable to use the filter for first time but when I reload the page it works fine. I also tried the 

```
"overrides": {
  "nuxt": {
    "ufo": "1.5.3"
  }
},
```

This did not work for me as well in `package.json`.

**Comment by Aravinda93** [comment] 2024-09-12 11:56
@richard-edwards 

I also used the `turbo` and added the recommendations in `overrides` as provided by @cameroncf but still see the issue and `queryContent` does not work for first time but if I load the page again then works for the 2nd time. This happens in production but is unable recreated locally.

Did you find a fix or work-around for this issue? I am using latest Nuxt and Nuxt content: `"turbo": "^2.0.9" "nuxt": "^3.13.1", "@nuxt/content": "^2.13.2",`.

I tried this but did not work for me:

```
"overrides": {
  "nuxt": {
    "ufo": "1.5.3"
  }
},
```

**Comment by Aravinda93** [comment] 2024-09-30 07:59
@richard-edwards @farnabaz @cameroncf @CharlieDigital @ABB65 @idesignzone @kevinhaeni

Guys, could you let me know if this issue was resolved? I am still seeing the problem and based on the provided approach I tried and did not work for me. I have added the comments above based on my observations.

Is there any workaround that I can use?

**Comment by Aravinda93** [comment] 2024-09-30 10:38
@farnabaz 

Kindly request you reopen this issue and lot of people are still facing the issue even with the latest Nuxt, Vue and Nuxt-content versions. I have created a reproduction of the issue in [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue)

Our production deployment is blocked due to this issue. Please provide some workaround.

**Comment by Aravinda93** [comment] 2024-09-30 10:57
@farnabaz 

Kindly request you reopen this issue and lot of people are still facing the issue even with the latest Nuxt, Vue and Nuxt-content versions. I have created a reproduction of the issue in [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue)

Our production deployment is blocked due to this issue. Please provide some workaround.


Steps for reproduction:

1. Navigate to  [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fpages%2Fdocs%2F%5B...slug%5D.vue) and run the application locally with command `npm run dev`.

2. Try to access any tags at the top the document by clicking on it `https://fx62n5-3000.csb.app/tags/event%20hash`

3. We can see the list of tags present in matching documents.

4. Now try to create `.output` by running `npm run generate` and try to run the website through it by running `npm install -g serve  & serve .output/public`

5. Now if we try to access then it wont work for the first time.
