### ISSUE TITLE
[Help] How to use main.css

### ISSUE THREAD

**Issue by derHodrig** [nuxt/content#919] opened 2021-07-09 08:10 UTC
Hello in the Nuxt Content Docu the is a section
https://content.nuxtjs.org/displaying#style

My question, how to use the main.css? I get a couple of syntax errors when I copy the CSS.

I use the Nuxt Tailwind Module but it seems there is a problem with that `apply` syntax

**Comment by derHodrig** [comment] 2021-07-09 10:51
If I check out the latest code from the docs theme and open it I get those errors
See: https://github.com/nuxt/content/blob/main/packages/theme-docs/src/assets/css/main.css

![image](https://user-images.githubusercontent.com/53934248/125066857-c68f9b00-e0b3-11eb-9583-faa8420c2dfc.png)

This seems not official CSS, why is it working in the docs theme?

it also happens in the Code group Component
See: https://github.com/nuxt/content/blob/main/packages/theme-docs/src/components/global/base/CodeGroup.vue

![image](https://user-images.githubusercontent.com/53934248/125067083-0e162700-e0b4-11eb-9b73-51816ec96f99.png)


I did not do any changes, installed the dependencies successfully. It's not an IDE problem, since I can't start the docs theme. Keep in mind, we are here in the scope of the raw docu theme, which is only available in the packages.

**Comment by NozomuIkuta** [comment] 2021-07-26 11:43
@derHodrig 

I'm not sure what is your question and goals.

But, if you are just interested in why Nuxt Content Theme Docs can use no-standard syntax CSS, that's because it uses [Nuxt TailwindCSS module](https://tailwindcss.nuxtjs.org), which extends CSS syntax (e.g. Sass-like nesting).

https://github.com/nuxt/content/blob/0b6a7be6f6287cde880b0d37c88e6461efa167ff/packages/theme-docs/src/index.js#L107

**Comment by derHodrig** [comment] 2021-07-26 12:06
This what you see in the images are the docs, what you described. I cant start the app because of this errors.

**Comment by NozomuIkuta** [comment] 2021-07-26 12:46
Hmm, then we can't help you without a reproduction or error messages you got.
It might be due to versioning of packages. It might be due to configuration of packages. So many possibilities that we can't specify...

**Comment by Tahul** [comment] 2022-05-09 12:18
Hey!

Could you provide more informations about your environment and maybe a reproduction of the issue?

I'm adding `v1` tag as we are moving priority support towards @nuxt/content v2.

As this issue is pretty old I'll be closing it, but feel free to reopen if needed!

Thank you a lot!

**Closed** 2022-05-09 12:18 UTC
Labels: question, pending-repro, v1
