### ISSUE TITLE
All attempts to load pages with queryContent on server results in error

### ISSUE THREAD

**Issue by VividLemon** [nuxt/content#1673] opened 2022-11-14 01:07 UTC
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.13.4`
- Builder:          `vite`
- User Config:      `css`, `build`, `vite`, `modules`
- Runtime Modules:  `@nuxt/content@2.2.1`, `@vueuse/nuxt@9.5.0`
- Build Modules:    `-`
------------------------------

### Reproduction

All I did was:
```
<template>
  <h1>Hello world</h1>
</template>

<script setup lang="ts">
// TODO this
const {data} = await useAsyncData('home', () => queryContent('/').findOne())
</script>

```

### Describe the bug

It creates a conflict and messes up some styles. Also creates other issues for the behavior of the site:

But it always comes out with these two errors. This only thing that occurs _on client_ when _refreshing the page_. It breaks any attempts on navigating from that page, and like I said, some styling issues. However, going to a fresh page, then navigating to that page, everything works fine. I figured that a high profile issue like this would not go unnoticed, so I must be doing something wrong. 

The files in my content dir are all yaml files. But in the example, the content doesn't exist, but still causes the same issue. 

As a side note, if I have a ./components dir, and don't have a ./components/content dir, even though it's empty, and I store my stuff at ./content. It warns me on server console about needing the ./components/content dir. Not sure why, or really what it's needed for :thinking: 

Some help would be appreciated.

### Additional context

Not really sure why this occurs. I haven't exactly tried it on a new project, but I have vuetify configured, if that matters. nuxt.config:
```
// "https"://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  css: ['vuetify/lib/styles/main.sass', '@mdi/font/css/materialdesignicons.min.css'],
  build: {
    transpile: ['vuetify'],
  },
  vite: {
    define: {
      'process.env.DEBUG': false,
    },
  },
  modules: ['@nuxt/content', '@vueuse/nuxt'],
})
```

### Logs

```shell
runtime-core.esm-bundler.js:6245 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'shapeFlag')
    at getNextHostNode (runtime-core.esm-bundler.js:6245:19)
    at getNextHostNode (runtime-core.esm-bundler.js:6246:20)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5715:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5745:56)
    at updateComponent (runtime-core.esm-bundler.js:5570:26)
    at processComponent (runtime-core.esm-bundler.js:5503:13)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at patchSuspense (runtime-core.esm-bundler.js:1237:13)
    at Object.process (runtime-core.esm-bundler.js:1188:13)
getNextHostNode @ runtime-core.esm-bundler.js:6245
getNextHostNode @ runtime-core.esm-bundler.js:6246
componentUpdateFn @ runtime-core.esm-bundler.js:5715
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
updateComponent @ runtime-core.esm-bundler.js:5570
processComponent @ runtime-core.esm-bundler.js:5503
patch @ runtime-core.esm-bundler.js:5101
patchSuspense @ runtime-core.esm-bundler.js:1237
process @ runtime-core.esm-bundler.js:1188
patch @ runtime-core.esm-bundler.js:5107
patchKeyedChildren @ runtime-core.esm-bundler.js:5865
patchChildren @ runtime-core.esm-bundler.js:5808
processFragment @ runtime-core.esm-bundler.js:5488
patch @ runtime-core.esm-bundler.js:5094
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
updateComponent @ runtime-core.esm-bundler.js:5570
processComponent @ runtime-core.esm-bundler.js:5503
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
updateComponent @ runtime-core.esm-bundler.js:5570
processComponent @ runtime-core.esm-bundler.js:5503
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
updateComponent @ runtime-core.esm-bundler.js:5570
processComponent @ runtime-core.esm-bundler.js:5503
patch @ runtime-core.esm-bundler.js:5101
patchKeyedChildren @ runtime-core.esm-bundler.js:5865
patchChildren @ runtime-core.esm-bundler.js:5808
patchElement @ runtime-core.esm-bundler.js:5321
processElement @ runtime-core.esm-bundler.js:5181
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
updateComponent @ runtime-core.esm-bundler.js:5570
processComponent @ runtime-core.esm-bundler.js:5503
patch @ runtime-core.esm-bundler.js:5101
patchKeyedChildren @ runtime-core.esm-bundler.js:5865
patchChildren @ runtime-core.esm-bundler.js:5808
processFragment @ runtime-core.esm-bundler.js:5488
patch @ runtime-core.esm-bundler.js:5094
patchKeyedChildren @ runtime-core.esm-bundler.js:5865
patchChildren @ runtime-core.esm-bundler.js:5808
patchElement @ runtime-core.esm-bundler.js:5321
processElement @ runtime-core.esm-bundler.js:5181
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
updateComponent @ runtime-core.esm-bundler.js:5570
processComponent @ runtime-core.esm-bundler.js:5503
patch @ runtime-core.esm-bundler.js:5101
patchKeyedChildren @ runtime-core.esm-bundler.js:5865
patchChildren @ runtime-core.esm-bundler.js:5808
processFragment @ runtime-core.esm-bundler.js:5488
patch @ runtime-core.esm-bundler.js:5094
patchKeyedChildren @ runtime-core.esm-bundler.js:5865
patchChildren @ runtime-core.esm-bundler.js:5808
patchElement @ runtime-core.esm-bundler.js:5321
processElement @ runtime-core.esm-bundler.js:5181
patch @ runtime-core.esm-bundler.js:5098
patchKeyedChildren @ runtime-core.esm-bundler.js:5865
patchChildren @ runtime-core.esm-bundler.js:5808
patchElement @ runtime-core.esm-bundler.js:5321
processElement @ runtime-core.esm-bundler.js:5181
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
(anonymous) @ runtime-core.esm-bundler.js:5743
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
triggerRefValue @ reactivity.esm-bundler.js:1003
set value @ reactivity.esm-bundler.js:1048
updateHasPrepend @ list.ts:32
(anonymous) @ VListItem.tsx:176
renderComponentRoot @ runtime-core.esm-bundler.js:898
hydrateSubTree @ runtime-core.esm-bundler.js:5603
componentUpdateFn @ runtime-core.esm-bundler.js:5624
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
hydrateNode @ runtime-core.esm-bundler.js:4730
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateFragment @ runtime-core.esm-bundler.js:4895
hydrateNode @ runtime-core.esm-bundler.js:4710
hydrateSubTree @ runtime-core.esm-bundler.js:5610
componentUpdateFn @ runtime-core.esm-bundler.js:5624
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
hydrateNode @ runtime-core.esm-bundler.js:4730
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateElement @ runtime-core.esm-bundler.js:4831
hydrateNode @ runtime-core.esm-bundler.js:4721
hydrateSubTree @ runtime-core.esm-bundler.js:5610
componentUpdateFn @ runtime-core.esm-bundler.js:5624
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
hydrateNode @ runtime-core.esm-bundler.js:4730
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateElement @ runtime-core.esm-bundler.js:4831
hydrateNode @ runtime-core.esm-bundler.js:4721
hydrateSubTree @ runtime-core.esm-bundler.js:5610
componentUpdateFn @ runtime-core.esm-bundler.js:5624
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
hydrateNode @ runtime-core.esm-bundler.js:4730
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateFragment @ runtime-core.esm-bundler.js:4895
hydrateNode @ runtime-core.esm-bundler.js:4710
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateElement @ runtime-core.esm-bundler.js:4831
hydrateNode @ runtime-core.esm-bundler.js:4721
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateElement @ runtime-core.esm-bundler.js:4831
hydrateNode @ runtime-core.esm-bundler.js:4721
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateFragment @ runtime-core.esm-bundler.js:4895
hydrateNode @ runtime-core.esm-bundler.js:4710
hydrateSubTree @ runtime-core.esm-bundler.js:5610
componentUpdateFn @ runtime-core.esm-bundler.js:5624
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
hydrateNode @ runtime-core.esm-bundler.js:4730
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateFragment @ runtime-core.esm-bundler.js:4895
hydrateNode @ runtime-core.esm-bundler.js:4710
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateElement @ runtime-core.esm-bundler.js:4831
hydrateNode @ runtime-core.esm-bundler.js:4721
hydrateChildren @ runtime-core.esm-bundler.js:4869
hydrateElement @ runtime-core.esm-bundler.js:4831
hydrateNode @ runtime-core.esm-bundler.js:4721
hydrateSubTree @ runtime-core.esm-bundler.js:5610
componentUpdateFn @ runtime-core.esm-bundler.js:5624
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
hydrateNode @ runtime-core.esm-bundler.js:4730
hydrateSubTree @ runtime-core.esm-bundler.js:5610
componentUpdateFn @ runtime-core.esm-bundler.js:5624
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
hydrateNode @ runtime-core.esm-bundler.js:4730
hydrateSuspense @ runtime-core.esm-bundler.js:1529
hydrateNode @ runtime-core.esm-bundler.js:4772
hydrateSubTree @ runtime-core.esm-bundler.js:5610
componentUpdateFn @ runtime-core.esm-bundler.js:5624
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
hydrateNode @ runtime-core.esm-bundler.js:4730
hydrate2 @ runtime-core.esm-bundler.js:4624
mount @ runtime-core.esm-bundler.js:4453
app.mount @ runtime-dom.esm-bundler.js:1626
initApp @ entry.mjs:49
await in initApp (async)
(anonymous) @ entry.mjs:57
runtime-dom.esm-bundler.js:35 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (runtime-dom.esm-bundler.js:35:30)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5713:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5745:56)
    at updateComponent (runtime-core.esm-bundler.js:5570:26)
    at processComponent (runtime-core.esm-bundler.js:5503:13)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at patchSuspense (runtime-core.esm-bundler.js:1297:13)
    at Object.process (runtime-core.esm-bundler.js:1188:13)
    at patch (runtime-core.esm-bundler.js:5107:26)
```
```

**Comment by farnabaz** [comment] 2022-11-17 11:20
I couldn't reproduce this issue, could you please provide a reproduction for it? You can use [content starter template](stackblitz.com/github/nuxt/starter/tree/content)

**Comment by VividLemon** [comment] 2022-11-17 13:33
I found that this line `<NuxtPage keep-alive :keep-alive-props="{max: 10}" />` breaks the app when refreshing on a page that has this: 
```
const {data} = await useAsyncData(`content-${path}`, () =>
  queryContent().where({_path: path}).findOne()
)
```

**Comment by VividLemon** [comment] 2022-11-26 17:14
Honestly, I've looked again, and it doesn't seem that it's _only_ keep-alive-props. I was doing some refactoring, and even adding a `style` attribute onto `<nuxt-page>` caused the same issues to occur. It has some weird interaction with, `nuxt-page`, `vuetify`, and `nuxt-content` under some specific circumstance. 
[content-app.zip](https://github.com/nuxt/content/files/10096692/content-app.zip)

**Comment by VividLemon** [comment] 2022-11-26 17:14
I've looked again, and it doesn't seem that it's _only_ keep-alive-props. I was doing some refactoring, and even adding a `style` attribute onto `<nuxt-page>` caused the same issues to occur. It has some weird interaction with, `nuxt-page`, `vuetify`, and `nuxt-content` under some specific circumstance. 
[content-app.zip](https://github.com/nuxt/content/files/10096692/content-app.zip)

**Comment by farnabaz** [comment] 2022-12-02 12:51
I believe this is not related to Content. I you remove the `queryContent` and push a simple promise in your page, you will see that the same error will raise. (just put `await Promise.resolve()` in setup script

I think this is related to Vuetify that tries to find the `v-main` height during rendering, but since the Nuxt uses suspense to await for async tasks, it  cannot find the Node and raise undefined error.

Wrapping `NuxtPage` in a `<div>` solves the issue.

I'm closing this issue, because its not related to Content.

**Closed by farnabaz** 2022-12-02 12:51 UTC
