### ISSUE TITLE
Cannot import components inside a markdown file

### ISSUE THREAD

**Issue by alihassan1133** [nuxt/content#261] opened 2020-07-14 05:13 UTC
![image](https://user-images.githubusercontent.com/62854082/87386592-dcd14c80-c56e-11ea-9e0c-0b27c9afa1bc.png)

```
<template>
    <div class="prose prose-lg mx-auto">
        <nuxt-content :document="page" />
    </div>
</template>

<script>
    export default {
        async asyncData ({ $content, params }) {
            const page = await $content(params.slug || 'index').fetch()

            return {
                page
            }
        }
    }
</script>
```

```md
---
title: Getting started
description: ''
---

<example></example>
```

### Steps to reproduce
1. Create a component inside the `components/` directory.
2. Try to include the component in a markdown file.

### What is Expected?
See the component on the web page when you navigate to the URL.

### What is actually happening?
Seeing an error in the console (screenshot attached.)

**Comment by HomyeeKing** [comment] 2020-07-14 12:17
I have a similiar situation, can not load the markdown files 
![image](https://user-images.githubusercontent.com/49113249/87424728-09d53c00-c60f-11ea-8dd2-96b7525201a3.png)

**Comment by benjamincanac** [comment] 2020-07-14 12:41
Hey @alihassan1133, you need to register the `<example>` component, you can either put your component inside `components/global/` to be imported automatically or import the component in your page.

**Comment by benjamincanac** [comment] 2020-07-14 12:47
@HomyeeKing It does not seem to be related, consider creating a new issue next time 🙂.

First of all, my advice would be to surround your `$content` call in a try/catch and call the nuxt `error` method so it doesn't crash and displays the error page from `layouts/error.vue`.

```js
async asyncData({ $content, params, error }) {
    let doc
    try {
      doc = await $content(params.slug || 'index').fetch()
    } catch (e) {
      return error({ statusCode: 404, message: 'Page not found' })
    }

    return {
        doc
    }
}
```

As for your error, it would be easier with a reproduction link but are your sure you have an `index.md` file inside `content/` folder?

**Comment by lucpotage** [comment] 2020-07-15 11:41
The documentation should help you. Everything is explained : https://content.nuxtjs.org/writing#global-components

**Comment by phiter** [comment] 2020-07-15 19:35
What if I don't want to use a component globally? Suppose I have a single component for a single blog page, how would I do that?

I would have only one markdown file and a vue file, where would I import the vue file?

**Comment by benjamincanac** [comment] 2020-07-16 08:44
@phiter You have to import the component in the page you use the `nuxt-content` component:

```vue
<script>
import Example from '~/components/example.vue'

export default {
    components: {
         Example
    }
}
</script>
```

**Comment by melnikovdv** [comment] 2020-07-16 14:57
I have the same problem. 

Imported as usual, it works in code, but when I move declaration to .md it fails with the same error. 

`<my-image src="/img/w1/logo.png"></my-image>`

**Comment by benjamincanac** [comment] 2020-07-20 15:00
Could you provide reproduction links so we help you out?

Thanks!

**Comment by benjamincanac** [comment] 2020-07-23 09:08
It seems there is an issue with local components registration in development due to live edit mode.

For now, to solve the issue you can put your components inside `components/global/` using Nuxt 2.13+ and setting `components: true` in your `nuxt.config.js`, see [Vue components](https://content.nuxtjs.org/writing#vue-components) > `Global components`.

You will also be able to disable the live edit feature once #125 is merged.

**Closed** 2020-08-06 10:51 UTC
Labels: bug

**Comment by mlazuardy** [comment] 2020-10-20 09:24
is this resolved ? in nuxt theme docs it can be override by adding

```
{
 components: [
//import components directory and global directory here
    {
      path: 'your custom component dir path',
      global: true
    }
  ]
}
```
