### ISSUE TITLE
Components in markdown using named slots not showing non-default names with `this.$slots`

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt/content#899] opened 2021-05-24 22:24 UTC
### Version
@nuxt/content: 1.11.1
nuxt: 2.15.5

### What prompted the bug?
1. I want to hide the wrapper divs if the slot is empty, which I think is a common use case.
2. Usually, we can do this with applying `v-if="$slots.slotname"` on the wrapper div.
3. But when I console logged `$slots` inside the component, I can only see default slot and not the named slot.
4. **Note: This bug is happening only for components used in markdown files. This bug doesn't exist if the same component is used in a normal `/pages` file.** So, maybe the issue lies with Nuxt Content, isn't it?  

### Steps to reproduce
1. Create a component called `abc.vue` having:
   ```html
   <template>
   <div>
     <slot name="test"></slot>
   </div>
   </template>
   ```

2. Use this in md file.
  ```md
  <abc>
  <template #test> some words</template>
   default content here
  </abc>
  ```

### What is Expected?
1. Inside the `abc.vue` component, when we console log `this.$slots`, we should be able to see an array containing info of both default and test slots. 

### What is actually happening?
1. `this.$slots` is showing only the default slot, and not the test slot.
2. But, strangely, the displaying part is working absolutely fine, i.e. the markdown is rendering correct content in DOM.

So, I am unable to use `v-if="this.$slots.test"` to hide my wrapper div.

**Comment by NozomuIkuta** [comment] 2021-05-25 17:27
I created a demo app and reproduced what @ManasMadrecha reported.

[CodeSandbox](https://codesandbox.io/s/nuxt-content-899-reproduction-odrz9)

**Comment by gsjen** [comment] 2021-05-27 00:38
While this is no doubt a bug, it's now recommended to always access slots using `$scopedSlots`: https://vuejs.org/v2/api/#vm-scopedSlots

**Comment by ManasMadrecha** [comment] 2021-05-27 13:07
@gsjen But we can't use scoped slots in markdown, can we? This is written on Content's website: https://content.nuxtjs.org/writing#vue-components

> However, you cannot render dynamic content nor use slot props. I.e., this wont work:
```
<my-component>
  <template #named-slot="slotProps">
    <p>{{ slotProps.someProperty }}</p>
  </template>
</my-component>
```

**Comment by NozomuIkuta** [comment] 2021-05-27 13:42
@ManasMadrecha 

The limitation is that we can't receive `slotProps` and use it inside slots, in markdown.
It is totally fine to use scoped slots without receiving `slotProps`, both in Nuxt Cntent's and Vue's perspectives.

As @gsjen said, all slots came to be exposed via `$scopedSlots` since Vue 2.6.0+.
So, Although Nuxt Content has a bug that you reported, we have "workaround" (it's recommended though) to access all slots.

> All $slots are now also exposed on $scopedSlots as functions. If you work with render functions, it is now recommended to always access slots via $scopedSlots, whether they currently use a scope or not. This will not only make future refactors to add a scope simpler, but also ease your eventual migration to Vue 3, where all slots will be functions.

**Comment by ManasMadrecha** [comment] 2021-05-27 14:58
@NozomuIkuta 

Keeping the same example in the first comment, I consoled log `this.$scopedSlots` in my `abc.vue` component which is being used in markdown, and it shows in the console just an empty `{}`. Now, not even the `default slot` content is seen in the console which was earlier seen with `$slots`. 😐

**Comment by farnabaz** [comment] 2022-05-31 10:23
As of @nuxt/content v2 introduce [MDC syntax](https://content.nuxtjs.org/guide/writing/mdc/) using Vue components inside markdown is much easier and you can  simply use slots inside you markdown. (However using dynamic content inside slots are not supported yet.)

```
::abc
`default` slot

#test
`test` slot
::
```

I am so closing this issue, but feel free to re-open if you still have the problem!.

**Closed by farnabaz** 2022-05-31 10:23 UTC
Labels: bug
