### ISSUE TITLE
Codesandbox examples don't work

### ISSUE THREAD

**Issue by borisdayma** [nuxt/content#584] opened 2020-10-18 18:14 UTC
### Version
@nuxt/content:  N/A
nuxt:  N/A

### Reproduction Link

The codesandbox examples don't work:
* [Basic usage](https://content.nuxtjs.org/examples/basic)
* [Docs theme](https://content.nuxtjs.org/examples/docs-theme/)
* [TailwindCSS Typography](https://content.nuxtjs.org/examples/tailwindcss-typography)

### Steps to reproduce
* Open one of the examples
* index page does not load
* about page actually works in the docs theme example

### What is Expected?
Index page should load

### What is actually happening?
Index page does not load

![image](https://user-images.githubusercontent.com/715491/96376231-4ef39780-1143-11eb-97c3-262329b2b62e.png)

**Comment by vividh** [comment] 2020-10-26 16:34
I'd like to help fix this.
This also seems a duplicate of https://github.com/nuxt/content/issues/564. Any idea what the issue is here?

**Comment by benjamincanac** [comment] 2020-10-27 16:38
This should be fixed.

**Closed by benjamincanac** 2020-10-27 16:38 UTC
Labels: bug
